import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F5F5F5' },
  center: { justifyContent: 'center', alignItems: 'center' },
  tabRow: { flexDirection: 'row', backgroundColor: '#FFF', elevation: 2 },
  tab: { flex: 1, padding: 14, alignItems: 'center', borderBottomWidth: 2, borderBottomColor: 'transparent' },
  tabActive: { borderBottomColor: '#0D47A1' },
  tabText: { color: '#757575', fontWeight: '500' },
  tabTextActive: { color: '#0D47A1', fontWeight: 'bold' },
  card: {
    backgroundColor: '#FFF',
    padding: 16,
    borderRadius: 8,
    marginBottom: 12,
    elevation: 2,
  },
  cardTitle: { fontSize: 18, fontWeight: 'bold', color: '#212121', marginBottom: 4 },
  cardDesc: { fontSize: 14, color: '#555', marginBottom: 8 },
  iconRow: { flexDirection: 'row', alignItems: 'center', marginVertical: 2 },
  iconText: { marginLeft: 6, fontSize: 13, color: '#555' },
  subLabel: { fontSize: 12, fontWeight: 'bold', color: '#333', marginTop: 4 },
  turnoText: { fontSize: 12, color: '#555' },
  button: {
    backgroundColor: '#0D47A1',
    paddingVertical: 10,
    borderRadius: 6,
    marginTop: 12,
    alignItems: 'center',
  },
  buttonText: { color: '#FFF', fontWeight: 'bold' },
  statusPill: {
    alignSelf: 'flex-start',
    color: '#FFF',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
    fontSize: 11,
    marginTop: 6,
    overflow: 'hidden',
  },
  motivo: { marginTop: 6, fontSize: 12, color: '#D32F2F', fontStyle: 'italic' },
  emptyText: { marginTop: 12, color: '#999' },
  floatingButton: {
    position: 'absolute',
    right: 16,
    bottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0D47A1',
    borderRadius: 22,
    paddingVertical: 10,
    paddingHorizontal: 14,
    elevation: 6,
  },
  floatingButtonText: {
    color: '#FFF',
    fontWeight: 'bold',
    marginLeft: 8,
  },
});
