import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F5F5F5' },
  center: { justifyContent: 'center', alignItems: 'center' },
  title: { fontSize: 22, fontWeight: 'bold', color: '#212121' },
  desc: { fontSize: 14, color: '#555', marginTop: 4, marginBottom: 16 },
  label: { fontWeight: 'bold', color: '#333', marginTop: 12, marginBottom: 6 },
  input: {
    borderWidth: 1,
    borderColor: '#DDD',
    borderRadius: 6,
    padding: 10,
    backgroundColor: '#FFF',
  },
  chipsRow: { flexDirection: 'row', flexWrap: 'wrap' },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    margin: 4,
    borderRadius: 16,
    backgroundColor: '#EEE',
  },
  chipActive: { backgroundColor: '#0D47A1' },
  chipText: { color: '#333' },
  chipTextActive: { color: '#FFF', fontWeight: 'bold' },
  termsBox: {
    backgroundColor: '#FFFDE7',
    padding: 10,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#FFE082',
    marginTop: 12,
  },
  termsTitle: { fontWeight: 'bold', marginBottom: 4 },
  termsTxt: { fontSize: 12, color: '#555' },
  row: { flexDirection: 'row', alignItems: 'center', marginTop: 12 },
  warn: { color: '#D32F2F', marginVertical: 6 },
  button: {
    backgroundColor: '#0D47A1',
    paddingVertical: 12,
    borderRadius: 6,
    marginTop: 16,
    alignItems: 'center',
  },
  buttonText: { color: '#FFF', fontWeight: 'bold', fontSize: 15 },
  secondaryButton: {
    borderWidth: 1,
    borderColor: '#0D47A1',
    paddingVertical: 12,
    borderRadius: 6,
    marginTop: 10,
    alignItems: 'center',
    backgroundColor: '#FFF',
  },
  secondaryButtonText: { color: '#0D47A1', fontWeight: 'bold', fontSize: 15 },
});
