import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F5F5F5' },
  center: { justifyContent: 'center', alignItems: 'center' },
  card: {
    backgroundColor: '#FFF',
    padding: 16,
    borderRadius: 8,
    marginBottom: 12,
    elevation: 2,
  },
  cardTitle: { fontSize: 17, fontWeight: 'bold', color: '#212121' },
  cardLine: { fontSize: 13, color: '#555', marginTop: 4 },
  inactiveBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#9E9E9E',
    color: '#FFF',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    fontSize: 11,
    marginTop: 6,
    overflow: 'hidden',
  },
  rowActions: { flexDirection: 'row', marginTop: 12, gap: 8 },
  btn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 6,
    alignItems: 'center',
  },
  btnPrimary: { backgroundColor: '#0D47A1' },
  btnDanger: { backgroundColor: '#D32F2F' },
  btnText: { color: '#FFF', fontWeight: 'bold' },

  fab: {
    position: 'absolute',
    right: 16,
    bottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0D47A1',
    borderRadius: 22,
    paddingVertical: 10,
    paddingHorizontal: 14,
    elevation: 6,
  },
  fabText: { color: '#FFF', fontWeight: 'bold', marginLeft: 8 },
  emptyText: { marginTop: 12, color: '#999' },

  // Form
  form: { padding: 16 },
  label: { fontSize: 13, color: '#555', marginTop: 12, marginBottom: 4, fontWeight: '600' },
  input: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#DDD',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    color: '#212121',
  },
  textarea: { minHeight: 70, textAlignVertical: 'top' },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 14,
  },
  switchLabel: { fontSize: 14, color: '#212121', flex: 1 },
  twoCols: { flexDirection: 'row', gap: 12 },
  flex1: { flex: 1 },

  turnoCard: {
    backgroundColor: '#FAFAFA',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: 6,
    padding: 12,
    marginTop: 8,
  },
  turnoRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  turnoRemove: { padding: 6 },
  addTurnoBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E3F2FD',
    paddingVertical: 10,
    borderRadius: 6,
    marginTop: 10,
  },
  addTurnoText: { color: '#0D47A1', fontWeight: 'bold', marginLeft: 6 },

  saveBtn: {
    backgroundColor: '#0D47A1',
    paddingVertical: 14,
    borderRadius: 6,
    alignItems: 'center',
    marginTop: 24,
  },
  saveBtnText: { color: '#FFF', fontWeight: 'bold', fontSize: 16 },
});
